name: flutter_projects
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.5
  flutter_riverpod: ^2.3.1
  geolocator: ^9.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  email_validator: ^2.1.17
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.0.18

  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  firebase_storage: ^11.0.15
  cloud_firestore: ^4.4.4
  dio: ^5.0.2
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0

  google_sign_in: ^6.0.2
  googleapis: ^10.1.0
  cached_network_image: ^3.2.3
  image_picker: ^0.8.7
  lottie: ^2.2.0
  ntp: ^2.0.0
  flutter_svg: ^2.0.3
  flutter_screenutil: ^5.7.0
  encrypt: ^5.0.1
  connectivity_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: sen
      fonts:
        - asset: assets/fonts/sen/Sen-Regular.ttf
        - asset: assets/fonts/sen/Sen-Bold.ttf
          weight: 700

    - family: dubai
      fonts:
        - asset: assets/fonts/dubai/Dubai-Regular.ttf
        - asset: assets/fonts/dubai/Dubai-Medium.ttf
          weight: 600
        - asset: assets/fonts/dubai/Dubai-Bold.ttf
          weight: 700

    - family: list
      fonts:
        - asset: assets/images/list_icon.ttf